server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/taskmaster
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    show-sql: true
    open-in-view: false
    database: postgresql
    generate-ddl: true
  sql:
    init:
      mode: never
      platform: postgres

